#!/bin/sh -eu

################################################################################

echo "====\n"
echo "Separate compilation + Zebra"

common_args="--snapshot 2010-01-01"
dict=test/cli/zebra/dictionary.toml
zebra_v2=test/cli/zebra/input.zbin2
zebra_v3=test/cli/zebra/input.zbin3

expected=test/cli/zebra/expected.psv
out_c=`mktemp -t icicle-c-XXXXXX`
out_psv_1=`mktemp -t icicle-out-1-XXXXXX`
out_psv_2=`mktemp -t icicle-out-2-XXXXXX`
drop=`mktemp -t icicle-drop-XXXXXX`

echo "Zebra v2"
dist/build/icicle/icicle query --dictionary-toml $dict --input-zebra $zebra_v2 --output-dense-psv $out_psv_1 $common_args

dist/build/icicle/icicle compile --dictionary-toml $dict --input-zebra  --output-dense-psv --output-code $out_c $common_args
dist/build/icicle/icicle query --dictionary-code $out_c --input-zebra $zebra_v2 --output-dense-psv $out_psv_2 $common_args

diff -u $expected $out_psv_1
diff -u $expected $out_psv_2

echo "Zebra v3"
dist/build/icicle/icicle query --dictionary-toml $dict --input-zebra $zebra_v3 --output-dense-psv $out_psv_1 $common_args

dist/build/icicle/icicle compile --dictionary-toml $dict --input-zebra  --output-dense-psv --output-code $out_c $common_args
dist/build/icicle/icicle query --dictionary-code $out_c --input-zebra $zebra_v3 --output-dense-psv $out_psv_2 $common_args

diff -u $expected $out_psv_1
diff -u $expected $out_psv_2


rm $out_c
rm $out_psv_1
rm $out_psv_2
rm $drop


