#!/bin/sh -eu

echo "1. Sanity test"

t1_dict=test/cli/bench/t1-dictionary.toml
t1_in=test/cli/bench/t1-in.psv

t1_expected=test/cli/bench/t1-expected.psv
t1_out_c=`mktemp -t icicle-bench-t1-c-XXXXXX`
t1_out_psv=`mktemp -t icicle-bench-t1-out-XXXXXX`

dist/build/icicle-bench/icicle-bench $t1_dict $t1_in $t1_out_psv $t1_out_c 2010-01-01

diff $t1_expected $t1_out_psv

rm $t1_out_c
rm $t1_out_psv

echo "OK!"

################################################################################

echo "2a. Dropping facts that exceed the limit: input sparse, output sparse"

t2_common_args="--input-psv sparse --output-psv sparse"
t2_dict=test/cli/bench/t2-dictionary.toml
t2_in=test/cli/bench/t2-in.psv

echo "Limit: 0 fact. Output should be empty. Drop log should point to the first fact for each entity."

t2_expected_psv_0=test/cli/bench/t2-expected-0.psv
t2_expected_drop_0=test/cli/bench/t2-drop-0.txt
t2_c_0=`mktemp -t icicle-bench-t2-c-0-XXXXXX`
t2_psv_0=`mktemp -t icicle-bench-t2-out-0-XXXXXX`
t2_drop_0=`mktemp -t icicle-bench-t2-drop-0-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2_dict $t2_in $t2_psv_0 $t2_c_0 2010-01-01 --facts-limit 0 --drop $t2_drop_0 $t2_common_args

diff $t2_expected_psv_0 $t2_psv_0
diff $t2_expected_drop_0 $t2_drop_0

rm $t2_c_0
rm $t2_psv_0
rm $t2_drop_0

echo "Limit: 1 fact. Output should be empty. Drop log should point to the second fact for each entity."

t2_expected_psv_1=test/cli/bench/t2-expected-1.psv
t2_expected_drop_1=test/cli/bench/t2-drop-1.txt
t2_c_1=`mktemp -t icicle-bench-t2-c-1-XXXXXX`
t2_psv_1=`mktemp -t icicle-bench-t2-out-1-XXXXXX`
t2_drop_1=`mktemp -t icicle-bench-t2-drop-1-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2_dict $t2_in $t2_psv_1 $t2_c_1 2010-01-01 --facts-limit 1 --drop $t2_drop_1 $t2_common_args

diff $t2_expected_psv_1 $t2_psv_1
diff $t2_expected_drop_1 $t2_drop_1

rm $t2_c_1
rm $t2_psv_1
rm $t2_drop_1

echo "Limit: 2 facts. Output should have bar and foooo. Drop log should point to the third fact for foo only."

t2_expected_psv_2=test/cli/bench/t2-expected-2.psv
t2_expected_drop_2=test/cli/bench/t2-drop-2.txt
t2_c_2=`mktemp -t icicle-bench-t2-c-2-XXXXXX`
t2_psv_2=`mktemp -t icicle-bench-t2-out-2-XXXXXX`
t2_drop_2=`mktemp -t icicle-bench-t2-drop-2-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2_dict $t2_in $t2_psv_2 $t2_c_2 2010-01-01 --facts-limit 2 --drop $t2_drop_2 $t2_common_args

diff $t2_expected_psv_2 $t2_psv_2
diff $t2_expected_drop_2 $t2_drop_2

rm $t2_c_2
rm $t2_psv_2
rm $t2_drop_2

echo "2b. Dropping facts that exceed the limit: input sparse, output dense"

t2b_common_args="--input-psv sparse --output-psv dense"
t2b_dict=test/cli/bench/t2b-dictionary.toml
t2b_in=test/cli/bench/t2b-in.psv

t2b_expected_psv=test/cli/bench/t2b-expected.psv
t2b_expected_drop=test/cli/bench/t2b-drop.txt
t2b_c=`mktemp -t icicle-bench-t2b-c-XXXXXX`
t2b_psv=`mktemp -t icicle-bench-t2b-out-XXXXXX`
t2b_drop=`mktemp -t icicle-bench-t2b-drop-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2b_dict $t2b_in $t2b_psv $t2b_c 2010-01-01 --facts-limit 1 --drop $t2b_drop $t2b_common_args

diff $t2b_expected_psv $t2b_psv
diff $t2b_expected_drop $t2b_drop

rm $t2b_c
rm $t2b_psv
rm $t2b_drop

echo "OK!"

################################################################################

echo "3a. Dropping facts that exceed the limit: input dense, output sparse"

t3_common_args="--input-psv dense --output-psv sparse"
t3_dict=test/cli/bench/t3-dictionary.toml
t3_in=test/cli/bench/t3-in.psv

echo "Max 2 facts"

t3_expected_psv_2=test/cli/bench/t3-expected.psv
t3_expected_drop_2=test/cli/bench/t3-drop.txt
t3_c_2=`mktemp -t icicle-bench-t3-c-XXXXXX`
t3_psv_2=`mktemp -t icicle-bench-t3-out-XXXXXX`
t3_drop_2=`mktemp -t icicle-bench-t3-drop-XXXXXX`

dist/build/icicle-bench/icicle-bench $t3_dict $t3_in $t3_psv_2 $t3_c_2 2016-01-01 --facts-limit 2 --drop $t3_drop_2 $t3_common_args

diff $t3_expected_psv_2 $t3_psv_2
diff $t3_expected_drop_2 $t3_drop_2

rm $t3_c_2
rm $t3_psv_2
rm $t3_drop_2

echo "3b. Dropping facts that exceed the limit: input dense, output dense"

t3b_common_args="--input-psv dense --output-psv dense"
t3b_dict=test/cli/bench/t3b-dictionary.toml
t3b_in=test/cli/bench/t3b-in.psv

t3b_expected_psv_2=test/cli/bench/t3b-expected.psv
t3b_expected_drop_2=test/cli/bench/t3b-drop.txt
t3b_c_2=`mktemp -t icicle-bench-t3b-c-XXXXXX`
t3b_psv_2=`mktemp -t icicle-bench-t3b-out-XXXXXX`
t3b_drop_2=`mktemp -t icicle-bench-t3b-drop-XXXXXX`

dist/build/icicle-bench/icicle-bench $t3b_dict $t3b_in $t3b_psv_2 $t3b_c_2 2016-01-01 --facts-limit 2 --drop $t3b_drop_2 $t3b_common_args

diff $t3b_expected_psv_2 $t3b_psv_2
diff $t3b_expected_drop_2 $t3b_drop_2

rm $t3b_c_2
rm $t3b_psv_2
rm $t3b_drop_2

echo "OK!"

################################################################################

echo "4. Output missing value"

t4_common_args="--input-psv sparse --output-psv dense"
t4_dict=test/cli/bench/t4-dictionary.toml
t4_in=test/cli/bench/t4-in.psv

t4_expected=test/cli/bench/t4-expected.psv
t4_out_c=`mktemp -t icicle-bench-t4-c-XXXXXX`
t4_out_psv=`mktemp -t icicle-bench-t4-out-XXXXXX`
t4_drop=`mktemp -t icicle-bench-t4-drop-XXXXXX`

dist/build/icicle-bench/icicle-bench $t4_dict $t4_in $t4_out_psv $t4_out_c 2010-01-01 --facts-limit 1000 --drop $t4_drop $t4_common_args

diff $t4_expected $t4_out_psv

rm $t4_out_c
rm $t4_out_psv
rm $t4_drop

echo "OK!"

