#!/bin/sh -eu

echo "1. Sanity test"

t1_dict=test/cli/bench/t1-dictionary.toml
t1_in=test/cli/bench/t1-in.psv

t1_expected=test/cli/bench/t1-expected.psv
t1_out_c=`mktemp -t icicle-bench-t1-c-XXXXXX`
t1_out_psv=`mktemp -t icicle-bench-t1-out-XXXXXX`

dist/build/icicle-bench/icicle-bench $t1_dict $t1_in $t1_out_psv $t1_out_c 2010-01-01

diff $t1_expected $t1_out_psv

rm $t1_out_c
rm $t1_out_psv

echo "OK!"


echo "2. Dropping facts that exceed the limit"

t2_dict=test/cli/bench/t2-dictionary.toml
t2_in=test/cli/bench/t2-in.psv

echo "Max 0 fact"

t2_expected_psv_0=test/cli/bench/t2-expected-0.psv
t2_expected_drop_0=test/cli/bench/t2-drop-0.txt
t2_c_0=`mktemp -t icicle-bench-t2-c-0-XXXXXX`
t2_psv_0=`mktemp -t icicle-bench-t2-out-0-XXXXXX`
t2_drop_0=`mktemp -t icicle-bench-t2-drop-0-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2_dict $t2_in $t2_psv_0 $t2_c_0 2010-01-01 0 $t2_drop_0 --discard-over-limit

diff $t2_expected_psv_0 $t2_psv_0
diff $t2_expected_drop_0 $t2_drop_0

rm $t2_c_0
rm $t2_psv_0
rm $t2_drop_0

echo "Max 1 fact"

t2_expected_psv_1=test/cli/bench/t2-expected-1.psv
t2_expected_drop_1=test/cli/bench/t2-drop-1.txt
t2_c_1=`mktemp -t icicle-bench-t2-c-1-XXXXXX`
t2_psv_1=`mktemp -t icicle-bench-t2-out-1-XXXXXX`
t2_drop_1=`mktemp -t icicle-bench-t2-drop-1-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2_dict $t2_in $t2_psv_1 $t2_c_1 2010-01-01 1 $t2_drop_1 --discard-over-limit

diff $t2_expected_psv_1 $t2_psv_1
diff $t2_expected_drop_1 $t2_drop_1

rm $t2_c_1
rm $t2_psv_1
rm $t2_drop_1

echo "Max 2 fact"

t2_expected_psv_2=test/cli/bench/t2-expected-2.psv
t2_expected_drop_2=test/cli/bench/t2-drop-2.txt
t2_c_2=`mktemp -t icicle-bench-t2-c-2-XXXXXX`
t2_psv_2=`mktemp -t icicle-bench-t2-out-2-XXXXXX`
t2_drop_2=`mktemp -t icicle-bench-t2-drop-2-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2_dict $t2_in $t2_psv_2 $t2_c_2 2010-01-01 2 $t2_drop_2 --discard-over-limit

diff $t2_expected_psv_2 $t2_psv_2
diff $t2_expected_drop_2 $t2_drop_2

rm $t2_c_2
rm $t2_psv_2
rm $t2_drop_2

echo "OK!"

