#!/bin/sh -eu

echo "1. Sanity test"

t1_dict=test/cli/bench/t1-dictionary.toml
t1_in=test/cli/bench/t1-in.psv

t1_expected=test/cli/bench/t1-expected.psv
t1_out_c=`mktemp -t icicle-bench-t1-c-XXXXXX`
t1_out_psv=`mktemp -t icicle-bench-t1-out-XXXXXX`

dist/build/icicle-bench/icicle-bench $t1_dict $t1_in $t1_out_psv $t1_out_c 2010-01-01

diff $t1_expected $t1_out_psv

rm $t1_out_c
rm $t1_out_psv

echo "OK!"

echo "2. Dropping facts that exceed the limit"

t2_dict=test/cli/bench/t2-dictionary.toml
t2_in=test/cli/bench/t2-in.psv

t2a_expected=test/cli/bench/t2a-expected.psv
t2a_out_c=`mktemp -t icicle-bench-t2a-c-XXXXXX`
t2a_out_psv=`mktemp -t icicle-bench-t2a-out-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2_dict $t2_in $t2a_out_psv $t2a_out_c 2010-01-01 1

diff $t2a_expected $t2a_out_psv

rm $t2a_out_c
rm $t2a_out_psv

t2b_expected=test/cli/bench/t2b-expected.psv
t2b_out_c=`mktemp -t icicle-bench-t2b-c-XXXXXX`
t2b_out_psv=`mktemp -t icicle-bench-t2b-out-XXXXXX`

dist/build/icicle-bench/icicle-bench $t2_dict $t2_in $t2b_out_psv $t2b_out_c 2010-01-01 2

diff $t2b_expected $t2b_out_psv

rm $t2b_out_c
rm $t2b_out_psv

echo "OK!"

