#!/bin/sh -eu

: ${UPDATE:="0"}

diff_update () {
    if [ "$UPDATE" = "1" ]; then
        echo Updating $1
        cat $2 > $1
    else
        diff -u $1 $2
    fi
}

################################################################################

echo "\nSeparate compilation + Zebra"
echo "============================"

common_args="--snapshot 2017-02-01"
dict=test/cli/zebra-nested/dictionary.toml
zebra_v2=test/cli/zebra-nested/input.zbin2
zebra_v3=test/cli/zebra-nested/input.zbin3

expected_psv=test/cli/zebra-nested/expected.psv
expected_schema=test/cli/zebra-nested/expected.schema.json
out_c=`mktemp -t icicle-c-XXXXXX`
out_psv_1=`mktemp -t icicle-out-1-XXXXXX`
out_schema_1=`mktemp -t icicle-out-schema-1-XXXXXX`
drop=`mktemp -t icicle-drop-XXXXXX`

echo "Zebra v3"
dist/build/icicle/icicle compile --input-toml $dict --output-c $out_c
dist/build/icicle/icicle query --dictionary-c $out_c --input-zebra $zebra_v3 --output-psv $out_psv_1 --output-psv-schema $out_schema_1 $common_args

diff_update $expected_psv $out_psv_1
diff_update $expected_schema $out_schema_1

rm $out_c
rm $out_psv_1
rm $out_schema_1
rm $drop
